### PR TITLE
ISSUE-583: 'readerSchemaVersion' in Kafka config key is marked as opt…

### LINKED ISSUE #583: 'readerSchemaVersion' in Kafka config key is marked as optional but effectively required due to Flux
Kafka Source has 'readerSchemaVersion' as `optional` config key and its default value is set to `null`.
But since Flux can't handle `null` value and throws an error, the key is effectively `required`.

Needs to change `readerSchemaVersion` to be `required`, or add a new constructor for AvroKafkaSpoutTranslator which excludes `readerSchemaVersion` from parameters so that it can be handled as `null`.

Moreover, we need to handle `empty string` as `null` for `readerSchemaVersion` as well since it throws NumberFormatException.

### PR DESCRIPTION
**Pull request by HeartSaVioR**
…ional but effectively required due to Flux

* add a new constructor for AvroKafkaSpoutTranslator which excludes readerSchemaVersion from parameters
* handle empty string as null for readerSchemaVersion as well since it throws NumberFormatException

This closes #583

### CODE REVIEW

File: streams/runners/storm/layout/src/main/java/com/hortonworks/streamline/streams/layout/storm/KafkaSpoutFluxComponent.java [hunk 1]
```diff
@@ -144,7 +144,15 @@ private String addRecordTranslator () {
                 .JSON_KEY_TOPIC}));
         constructorArgs.add(kafkaSource != null ? kafkaSource.getId() : "");
         constructorArgs.add(conf.get(TopologyLayoutConstants.SCHEMA_REGISTRY_URL));
-        constructorArgs.add(conf.get("readerSchemaVersion") != null ? Integer.parseInt((String) conf.get("readerSchemaVersion")) : null);
+
+        // add readerSchemaVersion to constructor arg only when it's not null and not empty
+        Object readerSchemaVersionObj = conf.get("readerSchemaVersion");
+        if (readerSchemaVersionObj != null) {
+            String readerSchemaVersion = (String) readerSchemaVersionObj;
+            if (!readerSchemaVersion.isEmpty()) {
```
Comment (satishd) [inline streams/runners/storm/layout/src/main/java/com/hortonworks/streamline/streams/layout/storm/KafkaSpoutFluxComponent.java]: nit: This can be simplified like below without having multiple ifs
```
String readerSchemaVersion = (String) conf.get("readerSchemaVersion");
if(readerSchemaVersion != null && !readerSchemaVersion.isEMpty()) {
    constructorArgs.add(Integer.parseInt(readerSchemaVersion))
}
```

Comment (HeartSaVioR) [inline streams/runners/storm/layout/src/main/java/com/hortonworks/streamline/streams/layout/storm/KafkaSpoutFluxComponent.java]: Thanks for the guide. Addressed.
